/**
 * src/types/poi.ts
 *
 * Core data model for Points of Interest (POIs).
 * These types are used throughout the app — from API responses,
 * to local storage, to UI rendering.
 */

/**
 * The category a POI belongs to. Used for filtering, prompt generation,
 * and icon selection in the UI.
 */
export type POICategory =
  | 'historical_landmark'
  | 'museum'
  | 'church'
  | 'park'
  | 'natural_landmark'
  | 'monument'
  | 'cultural_site'
  | 'quirky'
  | 'other';

/**
 * Represents a single Point of Interest along a trip.
 *
 * POIs are fetched from the Google Places API, curated/ranked by Gemini,
 * narrated by Gemini + TTS, and stored locally in SQLite.
 */
export interface POI {
  /** Unique identifier (UUID v4) */
  id: string;

  /** Human-readable name of the POI (e.g., "Colosseum") */
  name: string;

  /** Category classification — determines narration style and icon */
  category: POICategory;

  /** Geographic coordinates */
  coordinates: {
    lat: number;
    lng: number;
  };

  /** Google Places rating (1.0–5.0) */
  rating: number;

  /** Full narration text generated by Gemini */
  narration_text: string;

  /** Word count of the narration — used for estimated listen time */
  narration_word_count: number;

  /** Estimated listening duration in minutes (word_count / 150 wpm) */
  estimated_listen_minutes: number;

  /**
   * Local file path to the pre-generated audio file (.mp3).
   * Null if audio hasn't been generated yet (will fall back to device TTS).
   */
  audio_file_path: string | null;

  /**
   * Radius in meters within which this POI's narration is triggered.
   * City mode: ~50m, Route mode: ~3200m (~2 miles).
   */
  trigger_radius_meters: number;

  /** Priority score used for ordering (higher = more important) */
  priority: number;

  /** Remote URL for a representative image of the POI */
  image_url: string | null;

  /** Local file path if the image has been downloaded for offline use */
  image_local_path: string | null;

  /** Whether the user has bookmarked this POI */
  bookmarked: boolean;

  /** ISO 8601 timestamp of when the narration was played, or null if not yet played */
  played_at: string | null;

  /** Brief editorial description or summary of the POI (optional, from Places API) */
  description?: string | null;

  /** Total number of user ratings/reviews (optional, from Places API) */
  user_ratings_total?: number | null;
}

/**
 * Represents a single autocomplete recommendation from the Google Places API.
 */
export interface PlaceSuggestion {
  placeId: string;
  description: string;
  mainText: string;
}
